# 指定启动的服务名称:
services:
  - name: learner
    path: 'learner.py'
    num: 1
    kwargs:
      save_interval: 5
      TRAIN_EPOCH: 10
      NBATCH: 1
      CLIP_EPSILON: 0.2
      gamma: 0.99
      lam: 0.95
      critic_loss_coef: 0.5
      entropy_coef: 0.00155
      nopstepochs: 4
      lr: 0.001
      max_grad_norm: 0.75


  - name: actor
    path: 'actor.py'
    num: 1
  
# 指定需要启动的环境

envs:
  - name: env
    path: 'env.py'
    num: 5

log_dir: './log'
agent_type: "Continuous"
env_name: 'LunarLanderContinuous-v2'
ACTOR_MODEL_PATH: "model/actor.pth"
CRITIC_MODEL_PATH: "model/critic.pth"